### ISSUE TITLE
[UBER] preservation PROD storage migration #2

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/preservation_catalog#1558]
#### storage roots to be migrated
* services-disk13
* services-disk14
* services-disk15
* services-disk16
* services-disk18
* services-disk19
* services-disk20

####  here is the same list as a ruby string array, for easier rails console query usage:
```ruby
%w[services-disk13 services-disk14 services-disk15 services-disk16 services-disk18 services-disk19 services-disk20]
```

**Comment by jmartin-sul** [comment]
drawn from https://github.com/sul-dlss/preservation_catalog/issues/1465#issuecomment-611193512

## Week Before Cutover

Run M2C and C2M validation checks on Moabs and generate reports, for each storage root being migrated; details in the linked individual migration checklist issue for each root.  Different roots can be run in parallel for a given check, but the reports for each type of check should be run in sequence (i.e. all M2C before all C2M).

* _**TODO**_ notes from M2C run, including date/time of start/end, and summary of errors (if any).
* _**TODO**_ notes from C2M run, including date/time of start/end, and summary of errors (if any).

---

* services-diskN
    - [ ] M2C (run all objects, get report of all errors, not druids ...)
      - _log file output location_
    - [ ] C2M ditto
      - _log file output location_
* ...

**Comment by jmartin-sul** [comment]
drawn from https://github.com/sul-dlss/preservation_catalog/issues/1465#issuecomment-611195392

## Cutover Weekend - Shut Down Services Before Final Reports

NOTE:  ask Andrew/Julian how early (on Friday) you can shut down
- Preservation Robot Workers
- All Preservation Catalog Workers (we don't want validation jobs picked up before the storage is visible)
- ReST API for `/catalog` route
- weekend crons

SDR Manager:
   - [ ] is ready for accessioning to stop (including turning off Google Books accessioning)

Ops:
   - [ ] is ready to do the final backup of prescat database (but the actual snapshot will be taken after the shutdowns described in the rest of this comment)

### Shut Down Preservation Robots Workers

- [ ] (Ops) turn off nagios alerts for preservation_robots prod boxes
- [ ] look for running preservation robots workers in the resque GUI:  https://robot-console-prod.stanford.edu/workers
- [ ] shut off the workers manually by killing (only) the `resque-pool-master` process (`hotswap` interferes with other cap resque commands)

    ```sh
    # from the preservation_robots project on your laptop:
    $ bundle exec cap prod ssh

    # once you're on the preservation-robots1-prod server:
    $ ps -eaf | grep resque
    # look for line like this:
    # pres      1234     1  0 Feb18 ?        00:00:15 resque-pool-master[20200218172434]: managing [10204, 10207, 10210, 10214, 10219, 10223, 10228, 10235, 10239, 10242]
    $ kill -s QUIT [1234] # substitute the appropriate resque-pool-master pid, obviously
    $ ps -eaf | grep resque # confirm the workers aren't running
    ```
- [ ] ensure there are no running preservation robots workers in the resque GUI:  https://robot-console-prod.stanford.edu/workers
  - [ ] you might also do the same `ps -eaf | grep resque` as above as an extra cross-check

### Let the replicaton queues drain

Once preservation robots have been shutdown per the above, allow preservation catalog's `zipmaker`, `zips_made`, `s3_us_east_1_delivery`, `s3_us_west_2_delivery`, `ibm_us_south_delivery`, and `zip_endpoint_events` queues to drain to 0 before proceeding.  There is no need to worry about the `part_audit_*` queues.  We just want to make sure that anything that's already in the process of being replicated to the cloud finishes that process.  No new stuff should be queued up since the preservation robots will have been turned off already.

### If there are still jobs in the C2M queue, clear that queue

This queue will likely be drained by that point, but it should be safe to clear it if it isn't, since we'll queue everything on the new storage root for C2M later in this process (and everything else will get requeued the following Friday).

### Shut Down All Preservation Catalog Workers, ReST API, Weekend Cron Jobs

- [ ] (Ops) turn off nagios alerts for preservation_catalog prod boxes if they are still on
- [ ] create a shared_configs PR (***to base branch `preservation-catalog-prod`***) that sets all worker counts to 0

    `config/resque-pool.yml` should look like this:
    ```yml
    # c2m: 6
    # checksum_validation: 6
    # ibm_us_south_delivery: 6
    # m2c: 6
    # moab_replication_audit: 3
    # part_audit_aws_s3_east_1: 3
    # part_audit_aws_s3_west_2: 3
    # part_audit_ibm_us_south: 3
    # results_recorder: 6
    # s3_us_east_1_delivery: 6
    # s3_us_west_2_delivery: 6
    # zip_endpoint_events: 6
    # zipmaker: 6
    # zips_made: 6

    c2m: 0
    checksum_validation: 0
    ibm_us_south_delivery: 0
    m2c: 0
    moab_replication_audit: 0
    part_audit_aws_s3_east_1: 0
    part_audit_aws_s3_west_2: 0
    part_audit_ibm_us_south: 0
    results_recorder: 0
    s3_us_east_1_delivery: 0
    s3_us_west_2_delivery: 0
    zip_endpoint_events: 0 
    zipmaker: 0
    zips_made: 0
    ```

- [ ] have someone else merge shared_configs PR (if possible, or merge yourself)

- [ ] for preservation-catalog repo, rebase `migration-weekend` branch on top of the latest `master`

      `migration-weekend` should be just like a fresh `git pull` of master, with 5 additional commits), like this:

      ```
      29f52ad - (origin/migration-weekend, migration-weekend) comment out rest routes (56 minutes ago)
      0306871 - comment out weekend cron jobs (56 minutes ago)
      24d5822 - (origin/master, master) xxxxxx (22 hours ago)
      dfbce32 - also disable the zip cleanup cron job
      d1e3de6 - comment out other zip temp cleanup
      ```

      Note that `/resque` route is still functional in the `migration-weekend` branch

- [ ] force push the newly rebased `migration-weekend` branch back to github (necessary for deployment, which is done using the code as pushed to github)

- [ ] deploy `migration-weekend` branch to prod

      ```sh
      bundle exec cap prod deploy
      ```

- [ ] confirm there are no preservation catalog workers running via the resque GUI: https://preservation-catalog-prod-01.stanford.edu/resque/workers
- [ ] confirm the ReST routes are not available (e.g. via `rails routes`)
- [ ] confirm there are no weekend cron jobs, and no zip temp cleanup

      Note that cron jobs are deployed on preservation-catalog-prod-02 (technically there are also cron jobs defined on -04, but we're not concerned about them here).

      ```sh
      ssh pres@preservation-catalog-prod-02 'crontab -l'
      ssh pres@preservation-catalog-prod-04 'crontab -l'
      ```

      there should not be an uncommented line with `validate_expired_checksums!` in it, nor anything mentioning `/sdr-transfers`.


### Ops confirms the final storage sync looks good -- _GO/ABORT point_

Ops actually intends to do its last sync of content to the new storage here (Friday evening).  If there is some problem at this point with the final sync, we'll just quit the migration process, and then turn everything back on to its normal production state, as though nothing happened.

**Comment by jmartin-sul** [comment]
drawn from https://github.com/sul-dlss/preservation_catalog/issues/1465#issuecomment-611201964

## Cutover Weekend - Final Reports Before Adding New Disk, Ops confirms final catchup sync looks good

#### Final Pre-Cut-Over Reports
_**TODO**_:

_Date/Time of report run_:  reports generated, paths noted inline/below.  _**summary of any errors reported.  do the druid counts line up with what was expected from querying the DB?**_

_**TODO: list report output paths**_

```sh
cat <report paths> | wc -l
<wc results, should be count of migrated moabs, plus one header row for each file>
```

_**TODO: fill in with actual results**_
```ruby
[16] pry(main)> msr_names = %w[services-diskN ...]
[17] pry(main)> 
[18] pry(main)> CompleteMoab.joins(:moab_storage_root).where(moab_storage_roots: { name: msr_names }).count('1')
=> # <result>
[19] pry(main)> 
[20] pry(main)> msr_names.size
=> # <result>
```

12 storage roots, one header row per root, so line count in druid lists lines up with expected number of moabs from db query


* services-diskN
  - [ ] generate final pre-cutover report for objects with error status ```RAILS_ENV=production bundle exec rake prescat:reports:msr_moab_audit_errors[stor_root_name,b4_cutover]```
    - _location of output_
  - [ ] get list of druids on storage root ```RAILS_ENV=production bundle exec rake prescat:reports:msr_druids[storage_root_name,druids_b4]```
    - _location of output_
* ...


### Ops confirms the final storage sync looks good -- _GO/ABORT point_

- [ ] Ops actually intends to do its last sync of content to the new storage as this process starts (Friday evening).  If there is some problem at this point with the final sync (late Fri night/early Sat morning), we'll just quit the migration process, and then turn everything back on to its normal production state, as though nothing happened.

**Comment by jmartin-sul** [comment]
drawn from https://github.com/sul-dlss/preservation_catalog/issues/1465#issuecomment-611202680

## Cutover Weekend - Hand back to Ops for DB backup, Adding New Disk to Pres Catalog, Hand back to Ops for storage cutover

### Hand over to ops:

- [ ] Ops shuts down `httpd` on prod-01.  Ops has to do this via puppet, because if it's done as a one off on the VM command line, eventually puppet will just restart `httpd`.
- [ ] Ops completes the final backup of prescat database

### Back to infra dev:  Bring the Preservation Catalog web app back online

### Tell PresCat About New Storage Root

- [ ] update shared_configs for prescat with the new storage root information
  - [ ] create a shared_configs PR (***to base branch `preservation-catalog-prod`***) that adjusts storage root information (add the target storage root if not already present, comment by the origin roots, which will be replace by empty placeholder directories from pres cat's perspective).

    `storage_root_map.default` in `config/settings/production.yml` should have the target storage location on the new brick named and added

      ```yml
      storage_root_map:
        default:
          services-diskA: '/services-diskA' # migrated to pres-01 2020-??-??
          services-diskB: '/services-diskB' # migrated to pres-01 2020-??-??
          services-diskC: '/services-diskC' # migrated to pres-01 2020-??-??
          <snip>
          pres-01: '/pres-01'
          services-diskZ: '/services-diskZ'  # we want new content to go here, so it must be last, whichever active storage root is already last
      ```
  - [ ] have someone else merge shared_configs PR (if possible, or merge yourself)
- [ ] use capistrano to make prescat aware of new shared_configs
    ```sh
    bundle exec cap prod shared_configs:update
    ```
- [ ] if you added a new storage root (the first time migrating data to a particular new storage brick), you will need to add the root to the prescat db (run this from your laptop):
    ```sh
    bundle exec cap prod db_seed
    ```
    (yes, it's `db_seed` via capistrano)

### Update Affected Moabs In PresCat (gather pre-migration counts, run migration, gather post-migration counts)

#### pre-migration counts

- [ ] You will want the druid counts for each root.  From the rails console:
```ruby
pry(main)> CompleteMoab.joins(:preserved_object, :moab_storage_root).group(:storage_location).order('moab_storage_roots.storage_location asc').pluck('moab_storage_roots.storage_location, count(preserved_objects.druid)')
```

Record these query results, as you will use them for checking the state of things after running the `prescat:migrate_storage_root` rake tasks.

##### _DATE, TIME of query run_

```ruby
[1] pry(main)> msr_names = %w[services-diskN ...]
...
[6] pry(main)> CompleteMoab.joins(:preserved_object, :moab_storage_root).group(:storage_location).order('moab_storage_roots.storage_location asc').pluck('moab_storage_roots.storage_location, count(preserved_objects.druid)')
=> # query results
[7] pry(main)> 
[8] pry(main)> CompleteMoab.joins(:preserved_object, :moab_storage_root).where(moab_storage_roots: { name: msr_names }).group(:storage_location).order('moab_storage_roots.storage_location asc').pluck('moab_storage_roots.storage_location, count(preserved_objects.druid)')
=> # query results
[9] pry(main)> 
[10] pry(main)> CompleteMoab.joins(:moab_storage_root).where(moab_storage_roots: { name: msr_names }).count('1')
=> # query results
[11] pry(main)> # yay, count still matches count from last night!
```
#### running the migration

_**You should probably run the migrations in a `screen` session!  These can take a few minutes, and network connections can be flaky.**_

To track progress, from the rails console for e.g. storage root 4 vs the new storage root:

```ruby
pry(main)> sr4 = MoabStorageRoot.find_by(name: 'services-disk04')
pry(main)> sr4.complete_moabs.count  # count should go down
pry(main)> new_mr = MoabStorageRoot.find_by(name: 'pres-01')
pry(main)> new_mr.complete_moabs.count  # count should go up
```

The following can be run in parallel (Naomi did 3 at a time via separate terminal windows ssh'ed into VM)

_**TODO: fill this in**_
* services-diskN
  - [ ] migrate CompleteMoabs to new storage root  ```RAILS_ENV=production bundle exec rake prescat:migrate_storage_root[services-diskN,pres-01]```
    - _log file location from rake output_
* ...

### Verify that the database migration looks good

Once the migration rake tasks have all been successfully executed

- [ ] run the count query mentioned above:
```ruby
pry(main)> CompleteMoab.joins(:preserved_object, :moab_storage_root).group(:storage_location).order('moab_storage_roots.storage_location asc').pluck('moab_storage_roots.storage_location, count(preserved_objects.druid)')
```

- [ ] cross-check the results of that query with the result from running the same query before the migration rake tasks were run
  - [ ] confirm that there are no entries in the query results for the origin storage roots
  - [ ] confirm that the count of moabs on the target storage root has increased by the sum of the counts from the origin roots.
  - E.g., if migrating `root2`, `root3`, and `root4` to `new-root-1`, `new-root-1` should have as many additional moabs associated with it as `root2`, `root3`, and `root4` previously held altogether (and those three old roots should no longer appear in the count query results).

##### _DATE, TIME_:  results of the cross-check querying and whether the counts line up as expected...

_**TODO: fill in**_
```ruby
[65] pry(main)> msr_names = %w[services-diskN ...]
=> [...]
[66] pry(main)> 
[67] pry(main)> CompleteMoab.joins(:preserved_object, :moab_storage_root).group(:storage_location).order('moab_storage_roots.storage_location asc').pluck('moab_storage_roots.storage_location, count(preserved_objects.druid)')
=> # query results
[68] pry(main)> 
[69] pry(main)> CompleteMoab.joins(:preserved_object, :moab_storage_root).where(moab_storage_roots: { name: msr_names }).group(:storage_location).order('moab_storage_roots.storage_location asc').pluck('moab_storage_roots.storage_location, count(preserved_objects.druid)')
=> # query results, should be empty: []
[70] pry(main)> 
[71] pry(main)> MoabStorageRoot.find_by!(name: 'pres-01').complete_moabs.count
=> # query results
```

### Notify Ops 

- [ ] notify Ops that preservation-catalog is ready for their final steps

**Comment by jmartin-sul** [comment]
### Ops Runs with the Baton

#### Ops cross checks the database migration -- _GO/ABORT point_

- Ops will also look to make sure the database migration went according to plan.  If it didn't and we decide that we want to back out, they'll just restore DB to state it was in prior to rake tasks (likely using the snapshot they took).

If the DB migration looks successful to everyone...

#### Ops will now perform such tasks as the following

- final migration of data from old storage root to new
- migrated content moved to final location on new brick (see #1376 )
- apply puppet PR to add new brick to preservation robots and prescat as needed
- unmount the old storage root's NFS volume so that pres cat no longer has access to the contents, leaving empty `sdr2objects` and `deposit` directories in the path that previously mounted the storage root contents. (this will make the contents of the old storage invisible to pres cat without deleting the files where they actually reside)
- more ops-y things
- notify us the data is now available in its new home.

#### Ops brings back httpd on prod-01

Eventually, puppet will restart `httpd` if it's manually stopped from the VM without also reflecting that change in puppet.  As such, Ops will need to stop (and here, restart) `httpd` on prod-01.  Devs will want it going forward, since monitoring audit queues via Resque console is very important to the rest of the process.

**Comment by jmartin-sul** [comment]
## Back to Devs After Ops Says Data Available On New Storage

### Confirm that the old storage root's NFS volume has been unmounted

- [ ] The migrated moabs should no longer be visible in the old location (e.g., if migrating off of `services-disk02`, `/services-disk02/sdr2objects` should be present, but empty -- its moabs should only be available from the migration's target storage location). This will prevent pres cat from seeing the same moab in two places, which is currently unsupported.

**Comment by jmartin-sul** [comment]
## Re-enable only the M2C and C2M workers

that is, uncomment only the lines for them in the resque-pool.yml file in shared_configs for pres cat prod, so `config/resque-pool.yml` looks like this:

```
c2m: 6
# checksum_validation: 6
# ibm_us_south_delivery: 6
m2c: 6
# moab_replication_audit: 3
# part_audit_aws_s3_east_1: 3
# part_audit_aws_s3_west_2: 3
# part_audit_ibm_us_south: 3
# results_recorder: 6
# s3_us_east_1_delivery: 6
# s3_us_west_2_delivery: 6
# zip_endpoint_events: 6
# zipmaker: 6
# zips_made: 6
```

## C2M Report After Migration

- [ ] confirm that C2M workers for newly migrated objects are running via the resque GUI: https://preservation-catalog-prod-01.stanford.edu/resque/overview

Run C2M, then generate report once the C2M queue is drained.  You can kick of C2M for the storage root as follows:
```
# Use a screen session to do this!  The check is run asynchronously by Resque workers, but may take up to an hour for everything to queue up.
MoabStorageRoot.find_by(name: 'pres-01').c2m_check!
```

Do watch for Honeybadger errors while audit validations are running!

#### pres-01:
- [ ] C2M run completed _(C2M run has taken between 5 and 6 hours in the testing we've done, but things may be faster now)_
- [ ] C2M error report run ```RAILS_ENV=production bundle exec rake prescat:reports:msr_moab_audit_errors[stor_root_name,c2m_after]```
  - _report location from rake task output_
- [ ] C2M errors manually reviewed - _any new errors?_

**Comment by jmartin-sul** [comment]
drawn from https://github.com/sul-dlss/preservation_catalog/issues/1465#issuecomment-611220251

## M2C Report After Migration

M2C reports should be run **after** CV reports.  M2C can keep running after cutover (since we know we have all druids from storage root in the catalog).  You can check for M2C errors while it's running (run audit report) to see if anything surfaces (we hope not!)

Do check for honeybadger errors while audit validations are running.

#### pres-01:
- [ ] M2C run completed _(took just under 4.5 hours on the last migration)_
- [ ] M2C error report run ```RAILS_ENV=production bundle exec rake prescat:reports:msr_moab_audit_errors[stor_root_name,m2c_after]```
  - _report location from rake task output_
- [ ] M2C errors manually reviewed - no new errors

**Comment by jmartin-sul** [comment]
drawn from https://github.com/sul-dlss/preservation_catalog/issues/1465#issuecomment-611231022

#### queue management advice for the following couple weeks
We had vague worries during the last migration about rough edges in our resque lock config not properly de-duping CV jobs if we have stuff that will hang out in queue for days or weeks.  E.g. if locks expire too early, weekly CV queuing might queue druids that are already in queue from the migration weekend.  If this happens, you can clear the queue, and re-enqueue every moab with a null or expired fixity check date, as this date will be nulled out for all moved moabs.

## _Before Proceeding_ with the "After Migration Success" steps

Before bringing services back to normal, we have a meeting scheduled for 9 am Monday _**date for the Monday immediately after migration weekend**_ to confer on the status of the weekend's migration.  The folks from the infra dev team and the ops team who participated will be there, as well as @andrewjbtw.  As the repository manager, @andrewjbtw will give the final go ahead based on everyone else's report back before we bring things back online.

Additionally, Andrew will test accession a couple of items once systems are back online, and only after that's succeeded will user's be informed that they can start using the system again.

### If we decide the migration attempt was _not_ a success -- GO/ABORT point

##### _Decision_: **TBD**

_If_ we decide to rollback here, we will:
- [ ] Roll back Puppet changes
- [ ] Roll back shared_config changes
- [ ] Restore DB to state prior to rake tasks
- [ ] turn all systems back on

## After Migration Success - Update PresCat, PreservationRobots and TechMdService

### Restore Preservation Catalog Archival Workers, ReST API and weekend crons

- [ ] create a shared_configs PR (***to base branch `preservation-catalog-prod`***) that reverts the worker changes made above, keeps the new storage root (it must not be last) and removes the old storage roots.

    `config/resque-pool.yml` should look like this:
    ```yml
    c2m: 6
    checksum_validation: 6
    ibm_us_south_delivery: 6
    m2c: 6
    moab_replication_audit: 3
    part_audit_aws_s3_east_1: 3
    part_audit_aws_s3_west_2: 3
    part_audit_ibm_us_south: 3
    results_recorder: 6
    s3_us_east_1_delivery: 6
    s3_us_west_2_delivery: 6
    zip_endpoint_events: 6
    zipmaker: 6
    zips_made: 6
    ```

- [ ] also, add the new services disk (we're doing this before re-enabling all the workers on this migration run)
  `config/settings/production.yml` should look like this:
  ```yml
  services-disk02: '/services-disk02' # content migrated to pres-01 2020-04-24
  ...
  services-disk12: '/services-disk12' # content migrated to pres-01 2020-04-24
  services-disk13: '/services-disk13'
  ...
  services-disk16: '/services-disk16'
  services-disk17: '/services-disk17' # content migrated to pres-01 2020-04-24
  services-disk18: '/services-disk18'
  ...
  services-disk22: '/services-disk22'
  pres-01: '/pres-01'
  services-disk23: '/services-disk23' # we want new content to go here, so it must be last
  ...
  (... all the rest of configuration in production.yml ...)
  ```
- [ ] have someone else merge shared_configs PR (if possible, or merge yourself)
- [ ] deploy `master` branch of preservation_catalog to prod
    ```sh
    bundle exec cap prod deploy
    ```
- [ ] confirm there are archival workers running via the resque GUI: https://preservation-catalog-prod-01.stanford.edu/resque/overview
- [ ] confirm the ReST routes are available (e.g. go to https://preservation-catalog-prod-01.stanford.edu/v1/objects/wr934ny6689)
- [ ] confirm there are weekend cron jobs, especially CV
      Note that cron jobs are deployed on preservation-catalog-prod-02.
      ```sh
      bundle exec cap -z preservation-catalog-prod-02.stanford.edu prod ssh
      crontab -l
      ```
      there should be a line with `validate_expired_checksums!` in it.
- [ ] (Ops) turn on nagios alerts for preservation_catalog prod boxes

### Restore Preservation Robots Workers

- update shared_configs for preservation robots with the new storage root information
  - [ ] create a shared_configs PR (***to base branch `preservation_robots_prod`***) that adjusts storage root information.
    `moab.storage_roots` in `config/environments/prod.yml`  should have the target storage location on the new brick added, and the old storage root entry removed
      ```yml
      moab:
        storage_roots:
          - '/services-disk02' # content migrated to pres-01 2020-04-24
          - '/services-disk03' # content migrated to pres-01 2020-04-24
          <snip>
          - '/services-disk12' # content migrated to pres-01 2020-04-24
          - '/services-disk13'
          <snip>
          - '/services-disk16'
          - '/services-disk17' # content migrated to pres-01 2020-04-24
          - '/services-disk18'
          <snip>
          - '/services-disk22'
          - '/pres-01'
          - '/services-disk23'   # new content should continue going to services-disk23
      ```
  - [ ] have someone else merge shared_configs PR (if possible, or merge yourself)

- [ ] deploy `master` branch of preservation_robots to use the new shared_configs and to turn the workers back on
    ```sh
    bundle exec cap prod deploy
    ```
  - [ ] confirm your capistrano logs show the shared_configs being updated
  - [ ] confirm there are preservation robots workers available via the resque GUI:  https://robot-console-prod.stanford.edu/workers
- [ ] (Ops) turn on nagios alerts for preservation_robots prod boxes

### Update shared_configs for technical-metadata-service
- [ ] update shared_configs for technical-metadata-service with the new storage root information
- [ ] create a shared_configs PR (***to base branch `dor-techmd-prod`***) that adjusts storage root information.
    `storage_root_map.default` in `config/settings/production.yml` should have the target storage location on the new brick named and added, and the old storage root entry removed

      ```yml
      storage_root_map:
        default:
          services-disk02: '/services-disk02' # content migrated to pres-01 2020-04-24
          <snip>
          services-disk12: '/services-disk12' # content migrated to pres-01 2020-04-24
          services-disk13: '/services-disk13'
          <snip>
          services-disk13: '/services-disk16'
          services-disk17: '/services-disk17' # content migrated to pres-01 2020-04-24
          services-disk13: '/services-disk18'
          <snip>
          services-disk23: '/services-disk22'
          pres-01: '/pres-01'
          services-disk23: '/services-disk23'
      ```
  - [ ] deploy `master` branch of technical-metadata-service to use the new shared_configs
    ```sh
    bundle exec cap prod deploy
    ```
  - [ ] confirm your capistrano logs show the shared_configs being updated
